apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: calendar
  name: calendar
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: calendar
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: calendar
    spec:
      containers:
        - env:
            - name: GRPC_HOST
                valueFrom:
                  secretKeyRef:
                    name: {{ .Release.Name }}-secrets
                    key: user
            - name: GRPC_PORT
            - name: HTTP_HOST
            - name: HTTP_PORT
            - name: LOG_LEVEL
            - name: LOG_PATH
            - name: MIGRATION_PATH
            - name: POSTGRES_DSN
            - name: QUEUE_NAME
            - name: QUEUE_URL
            - name: SCHEDULER_CLEANUP_DAYS
            - name: SCHEDULER_INTERVAL
            - name: SENDER_LOG_LEVEL
            - name: STORAGE_TYPE
          image: calendar:develop
          name: calendar-app
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
