[logger]
level = "DEBUG"
path = "logs/access.log"

[psql]
dsn = "host=localhost port=5432 user=postgres password=postgres dbname=calendar sslmode=disable"
migration = "migrations"

[http]
host    = "0.0.0.0"
port    = "8080"

[Storage]
type    = "sql"