[logger]
level = "DEBUG"
path = "logs/access.log"

[psql]
dsn = "host=localhost port=5432 user=postgres password=postgres dbname=calendar sslmode=disable"
migration = "migrations"

[http]
host    = "127.0.0.1"
port    = "8080"

[grpc]
host  = "127.0.0.1"
port  = "50051"

[Storage]
type    = "sql"