[logger]
level = "${LOG_LEVEL}"
path = "${LOG_PATH}"

[psql]
dsn = "${POSTGRES_DSN}"
migration = "${MIGRATION_PATH}"

[http]
host = "${HTTP_HOST}"
port = "${HTTP_PORT}"

[grpc]
host = "${GRPC_HOST}"
port = "${GRPC_PORT}"

[storage]
type = "${STORAGE_TYPE}"

[queue]
url = "${QUEUE_URL}"
name = "${QUEUE_NAME}"

[scheduler]
intervalSeconds = ${SCHEDULER_INTERVAL}
cleanupOlderThanDays = ${SCHEDULER_CLEANUP_DAYS}

[sender]
logLevel = "${SENDER_LOG_LEVEL}"
