[logger]
level = "DEBUG"
path = "logs/access.log"

[psql]
dsn = "host=host.docker.internal port=5432 user=postgres password=postgres dbname=calendar sslmode=disable"
migration = "migrations"

[http]
host    = "0.0.0.0"
port    = "8080"

[grpc]
host  = "127.0.0.1"
port  = "50051"

[storage]
type    = "sql"

[queue]
url = "amqp://guest:guest@localhost:5672/"
name = "notifications"

[scheduler]
intervalSeconds = 10  # how often to check for upcoming events
cleanupOlderThanDays = 365

[sender]
logLevel = "info"